// AUTO-GENERATED BY clm unit penpot render (INV-CDO-11) — DO NOT HAND EDIT
// Generated from Penpot graph: 7f397ec9c40eae1de6f79619aecc8e8a718034f0d905c0c1a7645d0e74bf29c4
// Source archive hash:        bd6e5f3f61d36fe403446c1009d2b8706267314ac6001792668e19c9d2eacddb

export const PENPOT_GRAPH_HASH = "7f397ec9c40eae1de6f79619aecc8e8a718034f0d905c0c1a7645d0e74bf29c4";
export const PENPOT_ARCHIVE_HASH = "bd6e5f3f61d36fe403446c1009d2b8706267314ac6001792668e19c9d2eacddb";
export const STARTING_FRAME_ID = "d7570000-0000-8000-8000-000000000011";

export const NAVIGATION_ROUTES = [
  {
    "frameId": "d7570000-0000-8000-8000-000000000011",
    "name": "Home",
    "path": "index.html",
    "handle": "mcard:route:/index.html",
    "isStartingFrame": true,
    "links": [
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000012",
        "destinationHandle": "mcard:route:/app.html",
        "destinationPath": "app.html",
        "destinationName": "Mission Control",
        "eventType": "click"
      },
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000013",
        "destinationHandle": "mcard:route:/responsive-lab.html",
        "destinationPath": "responsive-lab.html",
        "destinationName": "Responsive UI Lab",
        "eventType": "click"
      }
    ]
  },
  {
    "frameId": "d7570000-0000-8000-8000-000000000012",
    "name": "Mission Control",
    "path": "app.html",
    "handle": "mcard:route:/app.html",
    "isStartingFrame": false,
    "links": [
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000011",
        "destinationHandle": "mcard:route:/index.html",
        "destinationPath": "index.html",
        "destinationName": "Home",
        "eventType": "click"
      }
    ]
  },
  {
    "frameId": "d7570000-0000-8000-8000-000000000013",
    "name": "Responsive UI Lab",
    "path": "responsive-lab.html",
    "handle": "mcard:route:/responsive-lab.html",
    "isStartingFrame": false,
    "links": [
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000011",
        "destinationHandle": "mcard:route:/index.html",
        "destinationPath": "index.html",
        "destinationName": "Home",
        "eventType": "click"
      }
    ]
  }
];

export function getRouteByPath(targetPath) {
  const norm = targetPath.startsWith('/') ? targetPath.slice(1) : targetPath;
  return NAVIGATION_ROUTES.find(r => r.path === norm || r.path === targetPath) || null;
}

export function getRouteByFrameId(frameId) {
  return NAVIGATION_ROUTES.find(r => r.frameId === frameId) || null;
}

export function getOutgoingLinks(frameId) {
  const r = getRouteByFrameId(frameId);
  return r ? r.links : [];
}
