// AUTO-GENERATED BY clm unit penpot render (INV-CDO-11) — DO NOT HAND EDIT
// Generated from Penpot graph: 1fbb8f3b1effb423b3683782f610e599f241c5f794186ef3f050ee6654ec6682
// Source archive hash:        47768d2f0fe243c9cf74a4400b7933975b09eb75729cce0a83592205cbae802c

export const PENPOT_GRAPH_HASH = "1fbb8f3b1effb423b3683782f610e599f241c5f794186ef3f050ee6654ec6682";
export const PENPOT_ARCHIVE_HASH = "47768d2f0fe243c9cf74a4400b7933975b09eb75729cce0a83592205cbae802c";
export const STARTING_FRAME_ID = "d7570000-0000-8000-8000-000000000011";

export const NAVIGATION_ROUTES = [
  {
    "frameId": "d7570000-0000-8000-8000-000000000011",
    "name": "Home",
    "path": "index.html",
    "handle": "mcard:route:/index.html",
    "isStartingFrame": true,
    "links": [
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000012",
        "destinationHandle": "mcard:route:/app.html",
        "destinationPath": "app.html",
        "destinationName": "Mission Control",
        "eventType": "click"
      },
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000013",
        "destinationHandle": "mcard:route:/responsive-lab.html",
        "destinationPath": "responsive-lab.html",
        "destinationName": "Responsive UI Lab",
        "eventType": "click"
      }
    ]
  },
  {
    "frameId": "d7570000-0000-8000-8000-000000000012",
    "name": "Mission Control",
    "path": "app.html",
    "handle": "mcard:route:/app.html",
    "isStartingFrame": false,
    "links": [
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000011",
        "destinationHandle": "mcard:route:/index.html",
        "destinationPath": "index.html",
        "destinationName": "Home",
        "eventType": "click"
      }
    ]
  },
  {
    "frameId": "d7570000-0000-8000-8000-000000000013",
    "name": "Responsive UI Lab",
    "path": "responsive-lab.html",
    "handle": "mcard:route:/responsive-lab.html",
    "isStartingFrame": false,
    "links": [
      {
        "destinationFrameId": "d7570000-0000-8000-8000-000000000011",
        "destinationHandle": "mcard:route:/index.html",
        "destinationPath": "index.html",
        "destinationName": "Home",
        "eventType": "click"
      }
    ]
  }
];

export function getRouteByPath(targetPath) {
  const norm = targetPath.startsWith('/') ? targetPath.slice(1) : targetPath;
  return NAVIGATION_ROUTES.find(r => r.path === norm || r.path === targetPath) || null;
}

export function getRouteByFrameId(frameId) {
  return NAVIGATION_ROUTES.find(r => r.frameId === frameId) || null;
}

export function getOutgoingLinks(frameId) {
  const r = getRouteByFrameId(frameId);
  return r ? r.links : [];
}
