#!/usr/bin/env python3
"""
Create Google Calendar events for each user's daily report.
"""
import json
import os
import sys
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

def create_calendar_event(service, calendar_id, user_name, date_str, summary_text, report_url, commit_count):
    """Create a calendar event for a user's daily report."""
    
    # Create event title
    event_title = f"Daily Report from {user_name} - {date_str}"
    
    # Create event description
    description = f"""Daily Development Report

User: {user_name}
Date: {date_str}
Commits: {commit_count}

Summary:
{summary_text}

Full Report: {report_url}

---
Generated by GitHub Actions
Repository: {os.environ.get('GITHUB_REPOSITORY', 'N/A')}
Workflow: Daily Commit Summary
"""
    
    # Create event
    event = {
        'summary': event_title,
        'description': description,
        'start': {
            'date': date_str,
            'timeZone': 'Asia/Makassar',
        },
        'end': {
            'date': date_str,
            'timeZone': 'Asia/Makassar',
        },
        'colorId': '9',  # Blue color
        'reminders': {
            'useDefault': False,
        },
    }
    
    # Insert event
    try:
        created_event = service.events().insert(
            calendarId=calendar_id,
            body=event
        ).execute()
        
        print(f"✅ Event created for {user_name}")
        print(f"   Event ID: {created_event['id']}")
        print(f"   Event Link: {created_event.get('htmlLink', 'N/A')}")
        return created_event
        
    except HttpError as e:
        print(f"❌ Error creating event for {user_name}: {e}")
        return None

def main():
    if len(sys.argv) < 3:
        print("Usage: create_calendar_events.py <upload_results.json> <processing_results.json>")
        sys.exit(1)
    
    upload_results_file = sys.argv[1]
    processing_results_file = sys.argv[2]
    
    # Load results
    with open(upload_results_file, 'r') as f:
        upload_results = json.load(f)
    
    with open(processing_results_file, 'r') as f:
        processing_results = json.load(f)
    
    # Load Google credentials
    credentials_json = os.environ.get('GOOGLE_CREDENTIALS')
    if not credentials_json:
        print("ERROR: GOOGLE_CREDENTIALS environment variable not set")
        sys.exit(1)
    
    credentials_info = json.loads(credentials_json)
    service_account_email = credentials_info.get('client_email')
    print(f"Service account: {service_account_email}")
    
    # Create credentials
    SCOPES = ['https://www.googleapis.com/auth/calendar']
    credentials = service_account.Credentials.from_service_account_info(
        credentials_info, scopes=SCOPES
    )
    
    # Build Calendar API service
    service = build('calendar', 'v3', credentials=credentials)
    
    # Hardcoded calendar ID
    calendar_id = 'f0a800fb2e065c7a82fe3d4ffc26a1620a39737e8bcdbbd9e1ab1d6728090894@group.calendar.google.com'
    
    # Verify calendar access
    try:
        target_calendar = service.calendars().get(calendarId=calendar_id).execute()
        print(f"✅ Calendar accessible: {target_calendar.get('summary', '(no summary)')}")
    except HttpError as e:
        print(f"❌ Error accessing calendar: {e}")
        print("Make sure the calendar is shared with the service account")
        sys.exit(1)
    
    # Get yesterday's date in WITA timezone (UTC+8)
    wita_tz = ZoneInfo('Asia/Makassar')
    yesterday = (datetime.now(wita_tz) - timedelta(days=1)).strftime('%Y-%m-%d')
    
    # Create events for each user
    event_results = {}
    
    for user_name in upload_results.keys():
        upload_data = upload_results[user_name]
        
        if not upload_data.get('has_commits'):
            print(f"\nSkipping {user_name} - no commits")
            event_results[user_name] = {
                'has_commits': False,
                'event_created': False
            }
            continue
        
        print(f"\n{'='*60}")
        print(f"Creating calendar event for {user_name}")
        print(f"{'='*60}")
        
        # Get report URL (prefer PDF)
        urls = upload_data.get('urls', {})
        report_url = urls.get('pdf') or urls.get('markdown') or 'No report URL available'
        
        # Get summary from processing results
        processing_data = processing_results.get(user_name, {})
        analysis = processing_data.get('analysis', {})
        
        # Create summary text from first 3 summary points
        summary_points = analysis.get('summary', [])
        if summary_points:
            summary_text = '\n'.join([f"• {point}" for point in summary_points[:3]])
        else:
            summary_text = "No summary available"
        
        commit_count = upload_data.get('commit_count', 0)
        
        # Create event
        event = create_calendar_event(
            service,
            calendar_id,
            user_name,
            yesterday,
            summary_text,
            report_url,
            commit_count
        )
        
        event_results[user_name] = {
            'has_commits': True,
            'event_created': event is not None,
            'event_id': event['id'] if event else None,
            'event_link': event.get('htmlLink') if event else None
        }
    
    # Save event results
    from pathlib import Path
    event_results_file = Path('daily-reports') / 'calendar_events.json'
    with open(event_results_file, 'w') as f:
        json.dump(event_results, f, indent=2)
    
    print(f"\n{'='*60}")
    print(f"Calendar event results saved to: {event_results_file}")
    print(f"{'='*60}")
    
    # Print summary
    for user_name, data in event_results.items():
        if data['has_commits']:
            status = "✅" if data['event_created'] else "❌"
            print(f"{status} {user_name}: Event {'created' if data['event_created'] else 'failed'}")

if __name__ == '__main__':
    main()
