#!/usr/bin/env node
/**
 * penpot-render.mjs
 * Sprint CDO-15: Deliverable DV-CDO-15-04
 * Renders navigation artifacts (js/nav.js, index.html) from the Penpot navigation graph (INV-CDO-11).
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { extractNavigationGraph } from './penpot-nav.mjs';
import { sha256 } from './penpot-zip.mjs';
import { resolveUnitDir } from './penpot-init.mjs';

export function renderNavigationArtifacts(penpotFilePath, unitDir) {
  const resolvedUnit = resolveUnitDir(unitDir);
  const resolvedPenpot = path.resolve(penpotFilePath);

  if (!fs.existsSync(resolvedPenpot)) {
    throw new Error(`FILE_NOT_FOUND: Penpot design file not found at ${resolvedPenpot} (INV-CDO-08)`);
  }

  const graph = extractNavigationGraph(resolvedPenpot);
  const flow = graph.flows[0] || { startingFrame: null, name: 'default' };

  // Map frames to routes
  const frameMap = new Map();
  for (const f of graph.frames) {
    const handle = f.pluginData?.clm?.handle || '';
    // extract path from handle (e.g. "mcard:route:/index.html" -> "index.html" or "/index.html")
    let routePath = handle.replace(/^mcard:route:/, '');
    if (routePath.startsWith('/')) routePath = routePath.slice(1);
    if (!routePath) {
      if (f.name.toLowerCase().includes('home')) routePath = 'index.html';
      else if (f.name.toLowerCase().includes('mission')) routePath = 'app.html';
      else if (f.name.toLowerCase().includes('lab')) routePath = 'responsive-lab.html';
      else routePath = `${f.id}.html`;
    }
    frameMap.set(f.id, {
      ...f,
      routePath,
      handle: handle || `mcard:route:/${routePath}`,
    });
  }

  // 1. Render js/nav.js
  const navJsPath = path.join(resolvedUnit, 'js', 'nav.js');
  const navJsDir = path.dirname(navJsPath);
  if (!fs.existsSync(navJsDir)) fs.mkdirSync(navJsDir, { recursive: true });

  const routesList = Array.from(frameMap.values()).map(f => {
    const links = (f.interactions || []).map(inter => {
      const destFrame = frameMap.get(inter.destination);
      return {
        destinationFrameId: inter.destination,
        destinationHandle: destFrame?.handle || '',
        destinationPath: destFrame?.routePath || '',
        destinationName: destFrame?.name || '',
        eventType: inter.eventType || 'click',
      };
    });

    return {
      frameId: f.id,
      name: f.name,
      path: f.routePath,
      handle: f.handle,
      isStartingFrame: f.id === flow.startingFrame,
      links,
    };
  });

  const navJsContent = `// AUTO-GENERATED BY clm unit penpot render (INV-CDO-11) — DO NOT HAND EDIT
// Generated from Penpot graph: ${graph.meta.graphHash}
// Source archive hash:        ${graph.meta.archiveHash}

export const PENPOT_GRAPH_HASH = ${JSON.stringify(graph.meta.graphHash)};
export const PENPOT_ARCHIVE_HASH = ${JSON.stringify(graph.meta.archiveHash)};
export const STARTING_FRAME_ID = ${JSON.stringify(flow.startingFrame)};

export const NAVIGATION_ROUTES = ${JSON.stringify(routesList, null, 2)};

export function getRouteByPath(targetPath) {
  const norm = targetPath.startsWith('/') ? targetPath.slice(1) : targetPath;
  return NAVIGATION_ROUTES.find(r => r.path === norm || r.path === targetPath) || null;
}

export function getRouteByFrameId(frameId) {
  return NAVIGATION_ROUTES.find(r => r.frameId === frameId) || null;
}

export function getOutgoingLinks(frameId) {
  const r = getRouteByFrameId(frameId);
  return r ? r.links : [];
}
`;

  fs.writeFileSync(navJsPath, navJsContent, 'utf8');

  // 2. Render navigation markup into index.html
  const indexPath = path.join(resolvedUnit, 'index.html');
  let indexHtml = fs.readFileSync(indexPath, 'utf8');

  const navHtmlItems = routesList.map(r => {
    const activeClass = r.isStartingFrame ? ' penpot-nav-link-active' : '';
    return `      <a class="penpot-nav-link${activeClass}" href="${r.path}" data-penpot-frame="${r.frameId}" data-penpot-handle="${r.handle}">${r.name}</a>`;
  }).join('\n');

  const penpotNavBlock = `<!-- BEGIN: PENPOT-GENERATED-NAV (INV-CDO-11) -->
  <nav class="penpot-nav-bar" id="penpot-site-nav" aria-label="Penpot Navigation Flow" data-graph-hash="${graph.meta.graphHash}">
    <span class="penpot-nav-title">🎨 Flow: ${flow.name}</span>
    <div class="penpot-nav-links">
${navHtmlItems}
    </div>
  </nav>
  <!-- END: PENPOT-GENERATED-NAV -->`;

  const navBlockRegex = /<!-- BEGIN: PENPOT-GENERATED-NAV \(INV-CDO-11\) -->[\s\S]*?<!-- END: PENPOT-GENERATED-NAV -->/;

  if (navBlockRegex.test(indexHtml)) {
    indexHtml = indexHtml.replace(navBlockRegex, penpotNavBlock);
  } else {
    // Insert inside body right before <div class="top-controls"> or after <body>
    if (indexHtml.includes('<div class="top-controls">')) {
      indexHtml = indexHtml.replace('<div class="top-controls">', `${penpotNavBlock}\n\n  <div class="top-controls">`);
    } else if (indexHtml.includes('<body>')) {
      indexHtml = indexHtml.replace('<body>', `<body>\n  ${penpotNavBlock}\n`);
    } else {
      indexHtml = `${penpotNavBlock}\n${indexHtml}`;
    }
  }

  // Ensure module script tag for js/nav.js is present
  if (!indexHtml.includes('src="js/nav.js"') && !indexHtml.includes("src='./js/nav.js'")) {
    indexHtml = indexHtml.replace('</body>', `  <script type="module" src="js/nav.js"></script>\n</body>`);
  }

  // Ensure styling for .penpot-nav-bar is present
  if (!indexHtml.includes('.penpot-nav-bar')) {
    const styleSnippet = `
    /* Penpot Generated Navigation Bar (INV-CDO-11) */
    .penpot-nav-bar {
      position: absolute;
      top: 4.5rem;
      left: 1.5rem;
      display: flex;
      align-items: center;
      gap: 1rem;
      padding: 0.35rem 0.85rem;
      border-radius: 9999px;
      background: var(--color-surface, rgba(30, 41, 59, 0.7));
      border: 1px solid var(--color-border, rgba(255, 255, 255, 0.1));
      backdrop-filter: blur(var(--blur-surface, 12px));
      z-index: 60;
      font-size: 0.85rem;
    }
    .penpot-nav-title {
      font-weight: 600;
      color: var(--color-text-secondary, #94a3b8);
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .penpot-nav-links {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .penpot-nav-link {
      color: var(--color-text-primary, #f8fafc);
      text-decoration: none;
      padding: 0.2rem 0.5rem;
      border-radius: 6px;
      transition: background 150ms ease, color 150ms ease;
    }
    .penpot-nav-link:hover {
      background: var(--color-surface-hover, rgba(255, 255, 255, 0.1));
      color: #38bdf8;
    }
    .penpot-nav-link-active {
      background: rgba(59, 130, 246, 0.25);
      color: #60a5fa;
      font-weight: 600;
    }
`;
    indexHtml = indexHtml.replace('</style>', `${styleSnippet}\n  </style>`);
  }

  fs.writeFileSync(indexPath, indexHtml, 'utf8');

  return {
    ok: true,
    graphHash: graph.meta.graphHash,
    archiveHash: graph.meta.archiveHash,
    targets: [
      { path: navJsPath, size: fs.statSync(navJsPath).size },
      { path: indexPath, size: fs.statSync(indexPath).size },
    ],
  };
}

if (process.argv[1] && process.argv[1].endsWith('penpot-render.mjs')) {
  const args = process.argv.slice(2);
  let unitDir = 'LandingPage';
  let penpotFile = null;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--unit' && i + 1 < args.length) {
      unitDir = args[++i];
    } else if (!args[i].startsWith('-')) {
      if (fs.existsSync(args[i]) && fs.statSync(args[i]).isDirectory()) {
        unitDir = args[i];
      } else {
        penpotFile = args[i];
      }
    }
  }

  const resolvedUnit = resolveUnitDir(unitDir);
  if (!penpotFile) {
    penpotFile = path.join(resolvedUnit, 'design', 'landing-navigation.penpot');
  }

  try {
    const res = renderNavigationArtifacts(penpotFile, resolvedUnit);
    console.log(`✅ [penpot-render] Navigation artifacts successfully rendered:`);
    console.log(`   Graph Hash:   ${res.graphHash}`);
    console.log(`   Archive Hash: ${res.archiveHash}`);
    for (const t of res.targets) {
      console.log(`   Rendered:     ${t.path} (${t.size} bytes)`);
    }
    process.exit(0);
  } catch (err) {
    console.error(`❌ [penpot-render] Error: ${err.message}`);
    process.exit(1);
  }
}
